name: Pull request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn install --immutable
    - run: yarn build
    - run: sudo apt-get install luarocks
    - run: sudo luarocks install busted
    - working-directory: ./lua
      run: busted .
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - uses: ArtiomTr/jest-coverage-report-action@v2
      with:
          package-manager: yarn
          test-script: yarn jest
          github-token: ${{ secrets.GITHUB_TOKEN }}
  unity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: game-ci/unity-test-runner@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        projectPath: moontale-unity
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        unityVersion: 2021.1.5f1
